spring:
  application:
    name: system-services
  profiles:
    active: 8085  # Consider using a meaningful profile name instead of the port
  devtools:
    livereload:
      enabled: false
    add-properties: false
    restart:
      enabled: false

server:
  port: 8085
